### ISSUE TITLE
pmt returns NaN if interest rate is 0

### ISSUE THREAD

**Issue by etagwerker** [noverde/exonio#10]
Hi there! 

Thanks for all your work on this gem. It's saved me a lot of time in my project. 

I'm trying to use `Exonio.pmt` with an interest rate of 0 and I'm getting an unexpected result:

```
(byebug) interest_rate.to_s
"0.0"
(byebug) Exonio.pmt(interest_rate / 12, loan.amortization_schedule - month + 1, 0 - beginning_contract_balance)
#<BigDecimal:7ffd1dc47350,'NaN',9(45)>
```

In excel, it seems to work if I use a rate of 0: 

<img width="350" alt="screen shot 2018-07-13 at 11 17 17 am" src="https://user-images.githubusercontent.com/17584/42699290-5d9f7390-868e-11e8-8910-a152d3e7c39b.png">

I don't know enough about these formulas so I don't know what's the best solution. 

What could be the best patch for this? 

Please let me know.

Thanks!

**Comment by rmm5t** [comment]
Are we sure this issue should have been closed? I'm still seeing this issue with `pmt`.  The referenced PR fixed `nper`, not `pmt`.

```ruby
>> Exonio::VERSION
=> "0.7.0"
>> Exonio.pmt(0.0, 36, 36_000)
=> NaN
```

The expected value above should have been `1000`.

I think this ticket should be re-opened.

**Comment by julianolf** [comment]
Hi @rmm5t.

You are right; it seems we mistakenly closed this issue.

I'm reopening the issue and will take a look at your PR.
